-- BracketAI seed data
-- Run after supabase/schema.sql

begin;

insert into public.teams (
  id,
  name,
  short_name,
  seed,
  conference,
  record,
  wins,
  losses,
  offensive_rating,
  defensive_rating,
  net_rating,
  strength_of_schedule,
  three_point_pct,
  turnover_rate,
  turnovers_per_game,
  rebound_margin,
  ppg,
  opp_ppg,
  quad1_wins,
  quad1_losses,
  region
)
select *
from jsonb_to_recordset(

$$
[
  {
    "id": 1,
    "name": "Michigan",
    "short_name": "MICH",
    "seed": 1,
    "conference": "Big Ten",
    "record": "29-4",
    "wins": 29,
    "losses": 4,
    "offensive_rating": 122.6,
    "defensive_rating": 93.8,
    "net_rating": 28.8,
    "strength_of_schedule": 12.4,
    "three_point_pct": 38.9,
    "turnover_rate": 14.3,
    "rebound_margin": 8.1,
    "ppg": 81.4,
    "opp_ppg": 66.9,
    "quad1_wins": 11,
    "quad1_losses": 3,
    "region": "Midwest"
  },
  {
    "id": 2,
    "name": "Arizona",
    "short_name": "ARIZ",
    "seed": 1,
    "conference": "Big 12",
    "record": "28-5",
    "wins": 28,
    "losses": 5,
    "offensive_rating": 121.8,
    "defensive_rating": 95.1,
    "net_rating": 26.7,
    "strength_of_schedule": 11.7,
    "three_point_pct": 37.4,
    "turnover_rate": 15.1,
    "rebound_margin": 7.2,
    "ppg": 83.2,
    "opp_ppg": 69.4,
    "quad1_wins": 10,
    "quad1_losses": 4,
    "region": "West"
  },
  {
    "id": 3,
    "name": "Duke",
    "short_name": "DUKE",
    "seed": 1,
    "conference": "ACC",
    "record": "30-3",
    "wins": 30,
    "losses": 3,
    "offensive_rating": 123.1,
    "defensive_rating": 92.7,
    "net_rating": 30.4,
    "strength_of_schedule": 10.8,
    "three_point_pct": 39.1,
    "turnover_rate": 13.8,
    "rebound_margin": 8.8,
    "ppg": 82.6,
    "opp_ppg": 65.2,
    "quad1_wins": 12,
    "quad1_losses": 2,
    "region": "East"
  },
  {
    "id": 4,
    "name": "UConn",
    "short_name": "UCONN",
    "seed": 2,
    "conference": "Big East",
    "record": "27-6",
    "wins": 27,
    "losses": 6,
    "offensive_rating": 120.5,
    "defensive_rating": 94.6,
    "net_rating": 25.9,
    "strength_of_schedule": 10.2,
    "three_point_pct": 36.8,
    "turnover_rate": 14.5,
    "rebound_margin": 7.4,
    "ppg": 79.8,
    "opp_ppg": 67.8,
    "quad1_wins": 9,
    "quad1_losses": 5,
    "region": "East"
  },
  {
    "id": 5,
    "name": "Kansas",
    "short_name": "KU",
    "seed": 2,
    "conference": "Big 12",
    "record": "26-7",
    "wins": 26,
    "losses": 7,
    "offensive_rating": 119.3,
    "defensive_rating": 96.4,
    "net_rating": 22.9,
    "strength_of_schedule": 13.2,
    "three_point_pct": 35.9,
    "turnover_rate": 15.3,
    "rebound_margin": 6.3,
    "ppg": 78.5,
    "opp_ppg": 69.1,
    "quad1_wins": 10,
    "quad1_losses": 6,
    "region": "Midwest"
  },
  {
    "id": 6,
    "name": "Houston",
    "short_name": "HOU",
    "seed": 1,
    "conference": "Big 12",
    "record": "29-4",
    "wins": 29,
    "losses": 4,
    "offensive_rating": 118.6,
    "defensive_rating": 89.8,
    "net_rating": 28.8,
    "strength_of_schedule": 12.1,
    "three_point_pct": 37.2,
    "turnover_rate": 14.1,
    "rebound_margin": 9.5,
    "ppg": 77.3,
    "opp_ppg": 60.7,
    "quad1_wins": 12,
    "quad1_losses": 3,
    "region": "South"
  },
  {
    "id": 7,
    "name": "Purdue",
    "short_name": "PUR",
    "seed": 2,
    "conference": "Big Ten",
    "record": "27-6",
    "wins": 27,
    "losses": 6,
    "offensive_rating": 121.1,
    "defensive_rating": 97.1,
    "net_rating": 24.0,
    "strength_of_schedule": 11.4,
    "three_point_pct": 38.5,
    "turnover_rate": 14.9,
    "rebound_margin": 7.0,
    "ppg": 80.9,
    "opp_ppg": 68.6,
    "quad1_wins": 9,
    "quad1_losses": 5,
    "region": "Midwest"
  },
  {
    "id": 8,
    "name": "Auburn",
    "short_name": "AUB",
    "seed": 2,
    "conference": "SEC",
    "record": "28-5",
    "wins": 28,
    "losses": 5,
    "offensive_rating": 119.8,
    "defensive_rating": 93.9,
    "net_rating": 25.9,
    "strength_of_schedule": 11.9,
    "three_point_pct": 36.1,
    "turnover_rate": 15.5,
    "rebound_margin": 8.7,
    "ppg": 81.1,
    "opp_ppg": 66.1,
    "quad1_wins": 11,
    "quad1_losses": 4,
    "region": "South"
  },
  {
    "id": 9,
    "name": "Iowa State",
    "short_name": "ISU",
    "seed": 3,
    "conference": "Big 12",
    "record": "25-8",
    "wins": 25,
    "losses": 8,
    "offensive_rating": 116.4,
    "defensive_rating": 92.4,
    "net_rating": 24.0,
    "strength_of_schedule": 12.7,
    "three_point_pct": 35.2,
    "turnover_rate": 16.0,
    "rebound_margin": 6.4,
    "ppg": 75.2,
    "opp_ppg": 63.5,
    "quad1_wins": 8,
    "quad1_losses": 7,
    "region": "Midwest"
  },
  {
    "id": 10,
    "name": "St. John's",
    "short_name": "SJU",
    "seed": 3,
    "conference": "Big East",
    "record": "24-9",
    "wins": 24,
    "losses": 9,
    "offensive_rating": 114.9,
    "defensive_rating": 94.2,
    "net_rating": 20.7,
    "strength_of_schedule": 10.6,
    "three_point_pct": 34.7,
    "turnover_rate": 15.2,
    "rebound_margin": 5.8,
    "ppg": 74.1,
    "opp_ppg": 65.8,
    "quad1_wins": 7,
    "quad1_losses": 6,
    "region": "East"
  },
  {
    "id": 11,
    "name": "Florida",
    "short_name": "UF",
    "seed": 3,
    "conference": "SEC",
    "record": "25-8",
    "wins": 25,
    "losses": 8,
    "offensive_rating": 118.1,
    "defensive_rating": 96.0,
    "net_rating": 22.1,
    "strength_of_schedule": 11.5,
    "three_point_pct": 36.9,
    "turnover_rate": 14.7,
    "rebound_margin": 6.9,
    "ppg": 79.4,
    "opp_ppg": 69.7,
    "quad1_wins": 8,
    "quad1_losses": 6,
    "region": "South"
  },
  {
    "id": 12,
    "name": "Michigan State",
    "short_name": "MSU",
    "seed": 4,
    "conference": "Big Ten",
    "record": "24-9",
    "wins": 24,
    "losses": 9,
    "offensive_rating": 115.7,
    "defensive_rating": 95.6,
    "net_rating": 20.1,
    "strength_of_schedule": 10.9,
    "three_point_pct": 35.5,
    "turnover_rate": 14.8,
    "rebound_margin": 5.2,
    "ppg": 75.8,
    "opp_ppg": 67.0,
    "quad1_wins": 7,
    "quad1_losses": 7,
    "region": "Midwest"
  },
  {
    "id": 13,
    "name": "Tennessee",
    "short_name": "TENN",
    "seed": 2,
    "conference": "SEC",
    "record": "27-6",
    "wins": 27,
    "losses": 6,
    "offensive_rating": 117.5,
    "defensive_rating": 91.7,
    "net_rating": 25.8,
    "strength_of_schedule": 12.0,
    "three_point_pct": 35.7,
    "turnover_rate": 15.6,
    "rebound_margin": 7.6,
    "ppg": 76.6,
    "opp_ppg": 62.8,
    "quad1_wins": 10,
    "quad1_losses": 4,
    "region": "South"
  },
  {
    "id": 14,
    "name": "Wisconsin",
    "short_name": "WISC",
    "seed": 4,
    "conference": "Big Ten",
    "record": "23-10",
    "wins": 23,
    "losses": 10,
    "offensive_rating": 113.4,
    "defensive_rating": 96.9,
    "net_rating": 16.5,
    "strength_of_schedule": 10.4,
    "three_point_pct": 34.8,
    "turnover_rate": 13.6,
    "rebound_margin": 4.6,
    "ppg": 72.9,
    "opp_ppg": 66.8,
    "quad1_wins": 6,
    "quad1_losses": 8,
    "region": "Midwest"
  },
  {
    "id": 15,
    "name": "Marquette",
    "short_name": "MQ",
    "seed": 4,
    "conference": "Big East",
    "record": "24-9",
    "wins": 24,
    "losses": 9,
    "offensive_rating": 116.3,
    "defensive_rating": 97.3,
    "net_rating": 19.0,
    "strength_of_schedule": 10.1,
    "three_point_pct": 36.2,
    "turnover_rate": 14.4,
    "rebound_margin": 4.9,
    "ppg": 77.1,
    "opp_ppg": 69.2,
    "quad1_wins": 7,
    "quad1_losses": 6,
    "region": "East"
  },
  {
    "id": 16,
    "name": "Oregon",
    "short_name": "ORE",
    "seed": 5,
    "conference": "Big Ten",
    "record": "23-10",
    "wins": 23,
    "losses": 10,
    "offensive_rating": 114.2,
    "defensive_rating": 98.1,
    "net_rating": 16.1,
    "strength_of_schedule": 10.0,
    "three_point_pct": 35.4,
    "turnover_rate": 14.9,
    "rebound_margin": 4.1,
    "ppg": 74.8,
    "opp_ppg": 68.7,
    "quad1_wins": 6,
    "quad1_losses": 7,
    "region": "West"
  }
]

$$
::jsonb
) as t(
  id bigint,
  name text,
  short_name text,
  seed integer,
  conference text,
  record text,
  wins integer,
  losses integer,
  offensive_rating numeric(5,1),
  defensive_rating numeric(5,1),
  net_rating numeric(5,1),
  strength_of_schedule numeric(5,2),
  three_point_pct numeric(4,1),
  turnover_rate numeric(4,1),
  turnovers_per_game numeric(4,1),
  rebound_margin numeric(4,1),
  ppg numeric(4,1),
  opp_ppg numeric(4,1),
  quad1_wins integer,
  quad1_losses integer,
  region text
)
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  seed = excluded.seed,
  conference = excluded.conference,
  record = excluded.record,
  wins = excluded.wins,
  losses = excluded.losses,
  offensive_rating = excluded.offensive_rating,
  defensive_rating = excluded.defensive_rating,
  net_rating = excluded.net_rating,
  strength_of_schedule = excluded.strength_of_schedule,
  three_point_pct = excluded.three_point_pct,
  turnover_rate = excluded.turnover_rate,
  turnovers_per_game = excluded.turnovers_per_game,
  rebound_margin = excluded.rebound_margin,
  ppg = excluded.ppg,
  opp_ppg = excluded.opp_ppg,
  quad1_wins = excluded.quad1_wins,
  quad1_losses = excluded.quad1_losses,
  region = excluded.region;

insert into public.matchups (
  id,
  round,
  round_name,
  region,
  game_number,
  team_a_id,
  team_b_id,
  team_a_seed,
  team_b_seed,
  ai_pick_team_id,
  ai_confidence,
  ai_win_probability,
  ai_rationale
)
select *
from jsonb_to_recordset(

$$
[
  {
    "id": 101,
    "round": 1,
    "round_name": "Round of 64",
    "region": "Midwest",
    "game_number": 1,
    "team_a_id": 1,
    "team_b_id": 16,
    "team_a_seed": 1,
    "team_b_seed": 5,
    "ai_pick_team_id": 1,
    "ai_confidence": "high",
    "ai_win_probability": 72,
    "ai_rationale": "Michigan's half-court balance and elite shooting profile make them a strong favorite in this opening matchup."
  },
  {
    "id": 102,
    "round": 1,
    "round_name": "Round of 64",
    "region": "West",
    "game_number": 2,
    "team_a_id": 2,
    "team_b_id": 14,
    "team_a_seed": 1,
    "team_b_seed": 4,
    "ai_pick_team_id": 2,
    "ai_confidence": "medium",
    "ai_win_probability": 64,
    "ai_rationale": "Arizona's pace and offensive glass edge tilt this game, but Wisconsin's tempo control keeps it competitive."
  },
  {
    "id": 103,
    "round": 1,
    "round_name": "Round of 64",
    "region": "East",
    "game_number": 3,
    "team_a_id": 3,
    "team_b_id": 10,
    "team_a_seed": 1,
    "team_b_seed": 3,
    "ai_pick_team_id": 3,
    "ai_confidence": "high",
    "ai_win_probability": 69,
    "ai_rationale": "Duke's perimeter efficiency and rim protection create a strong two-way advantage over St. John's."
  },
  {
    "id": 104,
    "round": 1,
    "round_name": "Round of 64",
    "region": "East",
    "game_number": 4,
    "team_a_id": 4,
    "team_b_id": 15,
    "team_a_seed": 2,
    "team_b_seed": 4,
    "ai_pick_team_id": 4,
    "ai_confidence": "medium",
    "ai_win_probability": 61,
    "ai_rationale": "UConn's interior scoring and defensive rebounding profile give them the edge, but Marquette can flip it with hot shooting."
  },
  {
    "id": 105,
    "round": 1,
    "round_name": "Round of 64",
    "region": "Midwest",
    "game_number": 5,
    "team_a_id": 5,
    "team_b_id": 12,
    "team_a_seed": 2,
    "team_b_seed": 4,
    "ai_pick_team_id": 5,
    "ai_confidence": "tossup",
    "ai_win_probability": 54,
    "ai_rationale": "Kansas has the higher-end offense, but Michigan State's execution in late-clock possessions makes this close."
  },
  {
    "id": 106,
    "round": 1,
    "round_name": "Round of 64",
    "region": "South",
    "game_number": 6,
    "team_a_id": 6,
    "team_b_id": 11,
    "team_a_seed": 1,
    "team_b_seed": 3,
    "ai_pick_team_id": 6,
    "ai_confidence": "high",
    "ai_win_probability": 67,
    "ai_rationale": "Houston's defense and turnover pressure are a difficult matchup for Florida's live-ball decision-making."
  },
  {
    "id": 107,
    "round": 1,
    "round_name": "Round of 64",
    "region": "South",
    "game_number": 7,
    "team_a_id": 8,
    "team_b_id": 13,
    "team_a_seed": 2,
    "team_b_seed": 2,
    "ai_pick_team_id": 13,
    "ai_confidence": "upset_alert",
    "ai_win_probability": 47,
    "ai_rationale": "Tennessee's point-of-attack defense can disrupt Auburn's rhythm and force low-efficiency possessions."
  },
  {
    "id": 108,
    "round": 1,
    "round_name": "Round of 64",
    "region": "Midwest",
    "game_number": 8,
    "team_a_id": 7,
    "team_b_id": 9,
    "team_a_seed": 2,
    "team_b_seed": 3,
    "ai_pick_team_id": 7,
    "ai_confidence": "medium",
    "ai_win_probability": 58,
    "ai_rationale": "Purdue's half-court shot quality and spacing should offset Iowa State's defensive pressure for most stretches."
  }
]

$$
::jsonb
) as m(
  id bigint,
  round integer,
  round_name text,
  region text,
  game_number integer,
  team_a_id bigint,
  team_b_id bigint,
  team_a_seed integer,
  team_b_seed integer,
  ai_pick_team_id bigint,
  ai_confidence text,
  ai_win_probability numeric(4,1),
  ai_rationale text
)
on conflict (id) do update set
  round = excluded.round,
  round_name = excluded.round_name,
  region = excluded.region,
  game_number = excluded.game_number,
  team_a_id = excluded.team_a_id,
  team_b_id = excluded.team_b_id,
  team_a_seed = excluded.team_a_seed,
  team_b_seed = excluded.team_b_seed,
  ai_pick_team_id = excluded.ai_pick_team_id,
  ai_confidence = excluded.ai_confidence,
  ai_win_probability = excluded.ai_win_probability,
  ai_rationale = excluded.ai_rationale;

-- Keep identity sequences aligned after explicit IDs
select setval(pg_get_serial_sequence('public.teams', 'id'), coalesce((select max(id) from public.teams), 1), true);
select setval(pg_get_serial_sequence('public.matchups', 'id'), coalesce((select max(id) from public.matchups), 1), true);

commit;
